cvm-version: 0.7.3
cpus: 2
memory: 8192

containers:
  - name: "sev-probe"
    image: "ghcr.io/eidola-ai/tinfoil-sev-test/sev-probe@sha256:sha256:67e764b5691503c6cc5abb197784e2b592cd75acf8fe038b316a2de434dbbfed"
    env:
      - PORT: "8080"

shim:
  upstream-port: 8080
  paths:
    - /*
